default: &default
  url: *development

development: &development
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: consul_development

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *development

preproduction:
  <<: *development

production:
  <<: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: consul_test
